{
 "title": "ems仪表盘",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "SOC 电量",
   "type": "timeseries",
   "description": "电池荷电状态",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {},
    {
     "query": "from(bucket: \"ems\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bms_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"soc\")"
    }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "description": "温度趋势图",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ems\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bms_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")"
    }
   ]
  },
  {
   "title": "电压",
   "type": "timeseries",
   "description": "电压趋势图",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ems\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bms_telemetry\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")"
    }
   ]
  }
 ]
}