{
 "title": "EMS查询",
 "description": "EMS查询",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deviceId",
    "label": "设备id",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"ems\", tag: \"deviceId\")"
   }
  ]
 },
 "panels": [
  {
   "title": "温度查询",
   "type": "timeseries",
   "description": "温度查询",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ems\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"bms_telemetry\")\r\n  |> filter(fn: (r) => r.deviceId == \"${deviceId}\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "电压查询",
   "type": "timeseries",
   "description": "电压查询",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ems\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"bms_telemetry\")\r\n  |> filter(fn: (r) => r.deviceId == \"${deviceId}\")\r\n  |> filter(fn: (r) => r._field == \"voltage\")"
    }
   ]
  },
  {
   "title": "SOC电量",
   "type": "timeseries",
   "description": "SOC电量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"ems\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"bms_telemetry\")\r\n  |> filter(fn: (r) => r.deviceId == \"${deviceId}\")\r\n  |> filter(fn: (r) => r._field == \"soc\")"
    }
   ]
  }
 ]
}